In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/Users/anshumdev/Desktop/Python/ML/churn-platform/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [7]:
print(df.shape)

(7043, 21)

In [9]:
# we print random 5 value so we can see data properly because some time first five value not have some unique value
df.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5197,7566-DSRLQ,Female,0,Yes,No,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,110.15,7998.8,No
4289,2228-BZDEE,Female,0,No,No,54,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.10,1079.45,No
6367,0848-SOMKO,Male,0,No,No,70,No,No phone service,DSL,Yes,...,Yes,Yes,No,Yes,Two year,No,Bank transfer (automatic),48.40,3442.8,No
6368,2720-WGKHP,Male,1,No,No,2,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,94.00,181.7,Yes
5039,4713-LZDRV,Female,1,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,79.60,195.05,Yes

In [ ]:
df.columns. # see all the columns and understood what data given already

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [11]:
print("DATA TYPES")
print(df.dtypes)

DATA TYPES
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
print("MISSING VALUES")
print(df.isnull().sum()).  # no null values

MISSING VALUES
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [13]:
print(df['Churn'].value_counts())

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [18]:
# Drop customerID (useless)
df = df.drop('customerID', axis=1)

In [20]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce') # basically its convert object to int and also if " " to NaN

In [22]:
print(df.isnull().sum())

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [23]:
#Fix missing values in TotalCharges
# We fill with median, not mean
# Why median? Because mean gets affected by outliers, median doesn't
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

In [25]:
df['Churn']=df['Churn'].map({'Yes':1,'No':0})
print(df['Churn'].value_counts())

Churn
0    5174
1    1869
Name: count, dtype: int64

In [27]:
binary_columns = ['gender', 'Partner', 'Dependents', 
                  'PhoneService', 'PaperlessBilling']   # these columns have only value 0 or 1
for i in binary_columns :
    df[i] = df[i].map(lambda x:1 if x in ['Yes','Female'] else 0)

In [28]:
print(df[binary_columns].head(3))

   gender  Partner  Dependents  PhoneService  PaperlessBilling
0       1        1           0             0                 1
1       0        0           0             1                 0
2       0        0           0             1                 1

In [29]:
# now we have to do one hot encoding of those columns hove unique value more than 3
multi_columns = ['MultipleLines', 'InternetService', 'OnlineSecurity',
                 'OnlineBackup', 'DeviceProtection', 'TechSupport',
                 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']
df = pd.get_dummies(df, columns=multi_columns)

In [35]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [38]:
df.sample(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
2616,0,0,1,1,6,1,1,44.60,260.80,1,...,1,0,0,1,0,0,1,0,0,0
2628,1,0,0,0,1,1,1,83.40,83.40,0,...,1,0,0,1,0,0,0,0,0,1
4192,0,0,0,0,23,1,0,20.15,405.60,0,...,0,1,0,0,1,0,1,0,0,0
3965,1,1,1,0,52,1,1,106.50,5621.85,0,...,0,0,1,0,1,0,0,0,1,0
4766,1,0,0,0,71,1,1,113.15,7993.30,0,...,0,0,1,0,0,1,0,1,0,0